### ISSUE TITLE
[Bug] Mixin (debug) incompatibility with Polymer

### ISSUE THREAD

**Issue by magneticflux-** [isXander/Debugify#105]
### Bug Description

The mixin for MC-183776 conflicts with a mixin in [Polymer](https://github.com/Patbox/polymer).

### How to Reproduce?

1. Set the flag `-Dmixin.debug=true` to enable detailed mixin conflict logging (otherwise the error is silently ignored)
2. Install Polymer 0.2.0b and Debugify 2.0.0
3. Start Minecraft and look for the massive error message

### Expected Behavior

The mods should coexist and not overwrite behavior or crash.

### Version

2.0.0

### Mod Loader Version

1.19 - 0.17.1-beta

### Mod Loader

Quilt

### Logs or additional context

```
[17:06:37] [Render thread/INFO]: Mixing basic.client.mc183776.KeyboardMixin from debugify-common.mixins.json into net.minecraft.class_309
[17:06:37] [Render thread/INFO]: Mixing client.KeyboardMixin from quilt_screen.mixins.json into net.minecraft.class_309
[17:06:37] [Render thread/INFO]: Mixing client.KeyboardMixin from polymer.mixins.json into net.minecraft.class_309
[17:06:37] [Render thread/INFO]: Renaming synthetic method lambda$polymer_catchChange$0()V to mdae0462$lambda$polymer_catchChange$0$0 in polymer.mixins.json:client.KeyboardMixin
[17:06:37] [Render thread/ERROR]: /********************************************************************************************************************************************************************/
[17:06:37] [Render thread/ERROR]: /*                                                                          Invalid Mixin                                                                           */
[17:06:37] [Render thread/ERROR]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[17:06:37] [Render thread/ERROR]: /*     Action : APPLY                                                                                                                                               */
[17:06:37] [Render thread/ERROR]: /*      Mixin : dev.isxander.debugify.mixins.basic.client.mc183776.KeyboardMixin                                                                                    */
[17:06:37] [Render thread/ERROR]: /*     Config : debugify-common.mixins.json                                                                                                                         */
[17:06:37] [Render thread/ERROR]: /*      ModId : debugify                                                                                                                                            */
[17:06:37] [Render thread/ERROR]: /*      Phase : DEFAULT                                                                                                                                             */
[17:06:37] [Render thread/ERROR]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[17:06:37] [Render thread/ERROR]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException                                                                                   */
[17:06:37] [Render thread/ERROR]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[17:06:37] [Render thread/ERROR]: /*     Injection validation failed: Callback method onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in      */
[17:06:37] [Render thread/ERROR]: /*     debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin from mod debugify expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using       */
[17:06:37] [Render thread/ERROR]: /*     refmap common-common-refmap.json [INJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin -> Apply Injections ->  ->      */
[17:06:37] [Render thread/ERROR]: /*     PostInject ->                                                                                                                                                */
[17:06:37] [Render thread/ERROR]: /*     debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin->@Inject::onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/Call */
[17:06:37] [Render thread/ERROR]: /*     ackInfoReturnable;)V from mod debugify]                                                                                                                      */
[17:06:37] [Render thread/ERROR]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[17:06:37] [Render thread/ERROR]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method                                     */
[17:06:37] [Render thread/ERROR]: /*     onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in                                                   */
[17:06:37] [Render thread/ERROR]: /*     debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin from mod debugify expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using       */
[17:06:37] [Render thread/ERROR]: /*     refmap common-common-refmap.json [INJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin -> Apply Injections ->  ->      */
[17:06:37] [Render thread/ERROR]: /*     PostInject ->                                                                                                                                                */
[17:06:37] [Render thread/ERROR]: /*     debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin->@Inject::onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/Call */
[17:06:37] [Render thread/ERROR]: /*     ackInfoReturnable;)V from mod debugify]                                                                                                                      */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463)                                                            */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)                                                 */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)                                       */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)                                             */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)                                                  */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)                                                            */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)                                                      */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)                                                              */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)                                                       */
[17:06:37] [Render thread/ERROR]: /*         org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)                                                  */
[17:06:37] [Render thread/ERROR]: /*         org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243)                                             */
[17:06:37] [Render thread/ERROR]: /*         org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146)                                                           */
[17:06:37] [Render thread/ERROR]: /*         org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)                                                                  */
[17:06:37] [Render thread/ERROR]: /*         java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)                                                                                          */
[17:06:37] [Render thread/ERROR]: /*         net.minecraft.class_310.<init>(class_310.java:489)                                                                                                       */
[17:06:37] [Render thread/ERROR]: /*         net.minecraft.client.main.Main.main(Main.java:198)                                                                                                       */
[17:06:37] [Render thread/ERROR]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                           */
[17:06:37] [Render thread/ERROR]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)                                                         */
[17:06:37] [Render thread/ERROR]: /*         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                 */
[17:06:37] [Render thread/ERROR]: /*         java.base/java.lang.reflect.Method.invoke(Method.java:568)                                                                                               */
[17:06:37] [Render thread/ERROR]: /*         org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)                                                      */
[17:06:37] [Render thread/ERROR]: /*         org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)                                                                                            */
[17:06:37] [Render thread/ERROR]: /*         org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)                                                                                  */
[17:06:37] [Render thread/ERROR]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                           */
[17:06:37] [Render thread/ERROR]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)                                                         */
[17:06:37] [Render thread/ERROR]: /*         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                 */
[17:06:37] [Render thread/ERROR]: /*         java.base/java.lang.reflect.Method.invoke(Method.java:568)                                                                                               */
[17:06:37] [Render thread/ERROR]: /*         org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)                                                                                      */
[17:06:37] [Render thread/ERROR]: /*         org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)                                                                             */
[17:06:37] [Render thread/ERROR]: /*         org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)                                                                                          */
[17:06:37] [Render thread/ERROR]: /*         org.multimc.EntryPoint.listen(EntryPoint.java:127)                                                                                                       */
[17:06:37] [Render thread/ERROR]: /*         org.multimc.EntryPoint.main(EntryPoint.java:57)                                                                                                          */
[17:06:37] [Render thread/ERROR]: /********************************************************************************************************************************************************************/
[17:06:37] [Render thread/ERROR]: Mixin apply for mod debugify failed debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin -> net.minecraft.class_309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Injection validation failed: Callback method onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin from mod debugify expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap common-common-refmap.json [INJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin -> Apply Injections ->  -> PostInject -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin->@Inject::onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V from mod debugify]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin from mod debugify expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap common-common-refmap.json [INJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin -> Apply Injections ->  -> PostInject -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin->@Inject::onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V from mod debugify]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) [quilt-loader-0.17.1-beta.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_310.<init>(class_310.java:489) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.1-beta.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
[17:06:37] [Render thread/WARN]: Mixin transformation of net.minecraft.class_309 failed
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) [quilt-loader-0.17.1-beta.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_310.<init>(class_310.java:489) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.1-beta.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin] from phase [DEFAULT] in config [debugify-common.mixins.json] from mod [debugify] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin from mod debugify expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap common-common-refmap.json [INJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin -> Apply Injections ->  -> PostInject -> debugify-common.mixins.json:basic.client.mc183776.KeyboardMixin->@Inject::onSetGamemodeSelectionScreen(ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V from mod debugify]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:463) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	... 24 more
```

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
On closer inspection it looks like this has nothing at all to do with polymer but a bug in debugify itself. When converting from Quilt Mappings -> Yarn, no errors or warnings were produced about this.

**Comment by magneticflux-** [comment]
Wait, how did my issue even happen in the first place??? Polymer injects into `processF3`, but Debugify injects into `processDebugKeys`. I'll investigate other mods in case I missed one that `@Overwrites` it.

**Comment by magneticflux-** [comment]
My initial report was a red herring: it turns out the issue still happens with only Debugify installed! I'll see if I can pin down the root cause and make a PR to fix it.

**Comment by isXander** [comment]
I swear I committed it. Must have reverted for testing. Whoops!
