### ISSUE TITLE
[Bug] Incompability with Vulkan

### ISSUE THREAD

**Issue by andreasdc** [isXander/Debugify#110]
### Bug Description

The game crashes.

### How to Reproduce?

1. Add Vulkan.
2. Add Debugify.

### Version

1.18.2

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

### Logs or additional context

[03:33:21] [Render thread/ERROR]: Mixin apply for mod debugify failed debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> com.mojang.blaze3d.systems.RenderSystem: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::onPollEvents with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> Prepare Injections ->  -> handler$zib000$onPollEvents(JLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::onPollEvents with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> Prepare Injections ->  -> handler$zib000$onPollEvents(JLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
	at net.minecraft.client.main.Main.main(Main:194) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[03:33:21] [Render thread/ERROR]: Mixin apply for mod debugify failed debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> com.mojang.blaze3d.systems.RenderSystem: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::onPollEvents with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> Prepare Injections ->  -> handler$zib000$onPollEvents(JLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::onPollEvents with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> Prepare Injections ->  -> handler$zib000$onPollEvents(JLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2394) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2389) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:206) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[03:33:21] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2394) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2389) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:206) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2394) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2389) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:206) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2394) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2389) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:206) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin] from phase [DEFAULT] in config [debugify-common.mixins.json] from mod [debugify] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2394) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2389) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:206) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::onPollEvents with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin -> Prepare Injections ->  -> handler$zib000$onPollEvents(JLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2394) ~[?:?]
	at net.minecraft.client.MinecraftClient.addSystemDetailsToCrashReport(MinecraftClient:2389) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:206) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 8 more

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by yavko** [comment]
Are you using mesa zink?

**Comment by andreasdc** [comment]
> Are you using mesa zink?

I don't use it, what's that?

**Comment by yavko** [comment]
> > Are you using mesa zink?
> 
> I don't use it, what's that?

How do you use vulkan then?!?!?!?

**Comment by andreasdc** [comment]
https://github.com/xCollateral/VulkanMod

**Comment by yavko** [comment]
Wow this exists, I use [zink](https://docs.mesa3d.org/drivers/zink.html)

**Comment by andreasdc** [comment]
> Wow this exists, I use [zink](https://docs.mesa3d.org/drivers/zink.html)

How to use it? Is it better than the mod? VulkanMod works awesome in my situation. Zink is not maintaned anymore from what I saw.

**Comment by yavko** [comment]
Zinc is a mesa driver which translates opengl calls to vulkan, what you sent seems to rewrite the minecraft engine instead of translating like zinc, also zinc is maintained. Also to use it you need to use the mesa3d graphics drivers.

**Comment by andreasdc** [comment]
It sounds more complicated than the mod, do you have some sort of easy or plug&play tutorial?

**Comment by yavko** [comment]
> It sounds more complicated than the mod, do you have some sort of easy or plug&play tutorial?

Yeah, since its not a mod, here is how I do it, using mesa is easiest on linux, on windows its a pain, and for macOS its better to use something else that translates to metal

1. ensure mesa version is compiled with zink
2. use a launcher that supports adding environment variables
3. add a env `MESA_LOADER_DRIVER_OVERRIDE=zink`
4. launch

**Comment by andreasdc** [comment]
How to get to 1st step? How to get and compile mesa with zink? Other 3 steps look easy. 😇

**Comment by yavko** [comment]
> How to get to 1st step? How to get and compile mesa with zink? Other 3 steps look easy. innocent Also I'm on windows unfortunately

try this: https://github.com/pal1000/mesa-dist-win

**Comment by isXander** [comment]
Please keep issues topical!

Fixed in 821d792bd9bda87799ea547ba4d0fcf5c4188b40

**Comment by andreasdc** [comment]
> > How to get to 1st step? How to get and compile mesa with zink? Other 3 steps look easy. innocent Also I'm on windows unfortunately
> 
> try this: https://github.com/pal1000/mesa-dist-win

It doesn't work for me, can you post your discord tag maybe?

**Comment by andreasdc** [comment]
> Please keep issues topical!
> 
> Fixed in [821d792](https://github.com/isXander/Debugify/commit/821d792bd9bda87799ea547ba4d0fcf5c4188b40)

Will this be fixed on 1.18?

**Comment by yavko** [comment]
> > > How to get to 1st step? How to get and compile mesa with zink? Other 3 steps look easy. innocent Also I'm on windows unfortunately
> > 
> > 
> > try this: [pal1000/mesa-dist-win](https://github.com/pal1000/mesa-dist-win)
> 
> It doesn't work for me, can you post your discord tag maybe?

`yavko#3609`

**Comment by isXander** [comment]
> > Please keep issues topical!
> > 
> > Fixed in [821d792](https://github.com/isXander/Debugify/commit/821d792bd9bda87799ea547ba4d0fcf5c4188b40)
> 
> Will this be fixed on 1.18?

No.
