### ISSUE TITLE
[Bug] I can't run the game with the latest version of the mod for forge

### ISSUE THREAD

**Issue by Noahfrechette** [isXander/Debugify#146]
### Bug Description

![image](https://user-images.githubusercontent.com/73401157/184575815-af1340c9-0519-44b5-969d-2190441143bb.png)

I don't get why I can't load it

### How to Reproduce?

1. go to the minecraft launcher
2.  Click on start
3.  see error

### Expected Behavior

for it to run without this happening

### Version

2.3.3

### Fabric/Quilt Loader Version

Forge - 43.0.11 for 1.19.2

### Logs or additional context

[23:10:40] [main/ERROR]: Mixin config itshallnottick.mixins.json does not specify "minVersion" property
[23:10:40] [main/ERROR]: Mixin config rubidium.mixins.json does not specify "minVersion" property
[23:10:40] [main/ERROR]: Mixin config mixins.oculus.compat.sodium.json does not specify "minVersion" property
[23:10:40] [main/ERROR]: Mixin config debugify-common.mixins.json does not specify "minVersion" property
[23:10:40] [main/ERROR]: Mixin config debugify.mixins.json does not specify "minVersion" property
[23:10:40] [main/INFO]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[23:10:40] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.0.11, --gameDir, E:\Users\Noah\AppData\Roaming\curseforge\Instances\Shaders GOD, --assetsDir, E:\Users\Noah\AppData\Roaming\curseforge\Install\assets, --uuid, 1a6dbdd0ae8e4cf5b1488b7c5d9db07c, --username, NoahFrechette06, --assetIndex, 1.19, --accessToken, ????????, --clientId, NWMwZjU1ZmQtY2Q4Yy00OWI4LTk2YWItZWNmYjE5MjU0NWVm, --xuid, 2535433376392736, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[23:10:40] [main/INFO]: OptiFine was NOT detected.
[23:10:40] [main/INFO]: OptiFabric was NOT detected.
[23:10:40] [main/INFO]: Loaded configuration file for Rubidium: 29 options available, 0 override(s) found
[23:10:40] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[23:10:40] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will NOT be applied because OptiFine was NOT detected.
[23:10:44] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[23:10:44] [pool-3-thread-1/FATAL]: Mixin apply failed debugify-common.mixins.json:basic.server.mc121706.BowAttackGoalMixin -> net.minecraft.world.entity.ai.goal.RangedBowAttackGoal: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field f_25782_ was not located in the target class net.minecraft.world.entity.ai.goal.RangedBowAttackGoal. Using refmap common-common-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field f_25782_ was not located in the target class net.minecraft.world.entity.ai.goal.RangedBowAttackGoal. Using refmap common-common-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:202) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.main.Main.lambda$run$0(Main.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by RaptaG** [comment]
Forge is no longer supported.
