### ISSUE TITLE
[Bug]Incompatibility with Valkyrien Skies

### ISSUE THREAD

**Issue by Proxwian** [isXander/Debugify#190]
### Bug Description

For some reason, launching Debugify with Valkyrien Skies mod returns error code: 1 on launch. Separatly mods works well

I tried to turn off all of the fixes in file, but no luck

### Version

Forge 1.11.0

### Fabric/Quilt Loader Version

40.1.87

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Please post logs.

**Comment by LoSilopante** [comment]
> Please post logs.

I found the same issue on 1.18.2 Forge (40.2.1, latest), made a profile with only Valkyrien Skies, Debugify, and their dependecies.

The game closes with ExitCode:1 without a crashlog nor a log, there's only what's written on the output console:

```
Exception in thread "main" java.lang.module.ResolutionException: Module debugify contains package com.llamalad7.mixinextras, module MixinExtras exports package com.llamalad7.mixinextras to debugify
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:807)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```

**Comment by isXander** [comment]
Didn't realise this is for Forge. I don't update the forge versions anymore. Remove debugify.
