### ISSUE TITLE
[Bug] Cannot edit settings through GUI

### ISSUE THREAD

**Issue by imDaniX** [isXander/Debugify#201]
### Bug Description

There's no button to edit the settings in ModMenu. YACL 2.2.0 is installed (also tried 2.1.1 with same results).
![2023-01-23_15 08 53](https://user-images.githubusercontent.com/18292506/214036207-15003d59-f2d9-41f7-9276-ea283904fd7c.png)

### Version

v1.19.3+1.0

### Fabric/Quilt Loader Version

Fabric Loader 0.14.12 for 1.19.3

### Logs or additional context

[Mod list](https://hst.sh/ahegobeget.css).

An error when opening mods menu.
```
[15:00:33] [Render thread/INFO]: Generating YACL screen
[15:00:33] [Render thread/ERROR]: Error from mod 'debugify'
java.lang.IncompatibleClassChangeError: Found interface dev.isxander.yacl.api.YetAnotherConfigLib$Builder, but class was expected
	at dev.isxander.debugify.client.gui.ConfigGuiHelper.createConfigGui(ConfigGuiHelper.java:21) ~[Debugify-1.19.3+1.0.jar:?]
	at dev.isxander.debugify.client.integrations.ModMenuIntegration.lambda$getModConfigScreenFactory$0(ModMenuIntegration.java:16) ~[Debugify-1.19.3+1.0.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:54) ~[modmenu-5.0.2.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:114) ~[modmenu-5.0.2.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:392) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:383) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1049) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-5.0.2.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:332) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1225) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[Fabric%201.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
```

Fabric Loader 0.14.12 is not the most recent one, but the mod was built with 0.14.11, and 0.14.13 got out just a couple of days ago, so I don't really expect that being the case.

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
You must update to Debugify 1.19.3+1.1

**Comment by imDaniX** [comment]
Thanks. For some reason 1.19.3+1.0 is shown as featured on Modrinth. Not sure if you can control it, but if you can, you may consider changing it to get rid of inattentive folks like me :P
