### ISSUE TITLE
[Bug] Worlds don't load

### ISSUE THREAD

**Issue by DeadbushCarrot** [isXander/Debugify#252]
### Bug Description

Anytime you start a world it gos normal then freezes then unfreezes then softlocks. it becomes stuck at 100%

### How to Reproduce?

1 Click play
2 load anyworld
3 it get softlocks

### Expected Behavior

To load the world

### Version

1.20.1 V1.0

### Fabric/Quilt Loader Version

Latest versions for both

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by MeeniMc** [comment]
This error produced in a loop in the log. 
```
[21:46:07] [Render thread/ERROR] (Minecraft) Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_29089(long)" because "this.field_3690.field_1687" is null
	at net.minecraft.class_634.method_11079(class_634.java:984) ~[client-intermediary.jar:?]
	at net.minecraft.class_2761.method_11872(class_2761.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2761.method_11054(class_2761.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```


Relevant log piece: 
```
[21:45:52] [Render thread/WARN] (FabricLoader/Mixin) @Redirect conflict. Skipping fabric-item-api-v1.client.mixins.json:ClientPlayerInteractionManagerMixin from mod fabric-item-api-v1->@Redirect::fabricItemContinueBlockBreakingInject(Lnet/minecraft/class_1799;Lnet/minecraft/class_1799;)Z with priority 1000, already redirected by debugify.client.mixins.json:basic.mc176559.MultiPlayerGameModeMixin from mod debugify->@Redirect::isSameItem(Lnet/minecraft/class_1799;Lnet/minecraft/class_1799;)Z with priority 1000
[21:45:52] [Render thread/INFO] (WorldMap) World map session finalized.
[21:45:52] [Render thread/WARN] (FabricLoader/Mixin) @Redirect conflict. Skipping fabric-item-api-v1.client.mixins.json:ClientPlayerInteractionManagerMixin from mod fabric-item-api-v1->@Redirect::fabricItemContinueBlockBreakingInject(Lnet/minecraft/class_1799;Lnet/minecraft/class_1799;)Z with priority 1000, already redirected by debugify.client.mixins.json:basic.mc176559.MultiPlayerGameModeMixin from mod debugify->@Redirect::isSameItem(Lnet/minecraft/class_1799;Lnet/minecraft/class_1799;)Z with priority 1000
[21:45:52] [Render thread/ERROR] (Minecraft) Error executing task on Client
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_636 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_634.method_11120(class_634.java:401) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector fabricItemContinueBlockBreakingInject(Lnet/minecraft/class_1799;Lnet/minecraft/class_1799;)Z in fabric-item-api-v1.client.mixins.json:ClientPlayerInteractionManagerMixin from mod fabric-item-api-v1 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap client-fabric-item-api-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 21 more
```

**Comment by futamiyarn** [comment]
same

**Comment by JasonHorkles** [comment]
I've narrowed it down to the MC-176559 fix - disabling this fixes the issue for those who still want to use the rest of the mod
![image](https://github.com/isXander/Debugify/assets/51760372/ce0d9d78-a026-477e-8458-0c40621a43e1)

**Comment by 31j** [comment]
What operating system are you using? I have the same issue on Fedora Linux but I could not replicate the issue on Windows 11.

**Comment by 31j** [comment]
To consolidate the two bug requests, here is the log file from mine https://mclo.gs/P1ffB3k

**Comment by JasonHorkles** [comment]
Seems to be fixed in the latest version (the mod marks it as unavailable now anyways)

**Comment by isXander** [comment]
Please update to the latest version!

**Comment by DeadbushCarrot** [comment]
> Please update to the latest version!

Already did its working perfectly
