### ISSUE TITLE
[Bug] Ender dragon = Crash

### ISSUE THREAD

**Issue by TinyDerp** [isXander/Debugify#380]
### Bug Description

Server load ender dragon = crash
(ignore the outdated fabric proxy, it works fine and is not the issue (I tested it))
(I'm also using the minecart experiment)

### How to Reproduce?

Go to the end and crash.

### Expected Behavior

Go to the end and be a sigma by killing the ender dragon

### Version

1.21.4+1.0

### Fabric/Quilt Loader Version

Fabric 0.16.9

### **Server:**
```
---- Minecraft Crash Report ----

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-12-23 21:00:44
Description: Exception ticking world

java.lang.ExceptionInInitializerError
	at knot//net.minecraft.world.entity.boss.enderdragon.EnderDragon.defineSynchedData(EnderDragon.java:159)
	at knot//net.minecraft.world.entity.Entity.<init>(Entity.java:323)
	at knot//net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:280)
	at knot//net.minecraft.world.entity.Mob.<init>(Mob.java:147)
	at knot//net.minecraft.world.entity.boss.enderdragon.EnderDragon.<init>(EnderDragon.java:104)
	at knot//net.minecraft.world.entity.EntityType.create(EntityType.java:597)
	at knot//net.minecraft.world.level.dimension.end.EndDragonFight.createNewDragon(EndDragonFight.java:494)
	at knot//net.minecraft.world.level.dimension.end.EndDragonFight.findOrCreateDragon(EndDragonFight.java:305)
	at knot//net.minecraft.world.level.dimension.end.EndDragonFight.tick(EndDragonFight.java:251)
	at knot//net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:374)
	at knot//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1069)
	at knot//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:953)
	at knot//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:713)
	at knot//net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:292)
	at java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1518 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@23.0.1/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	at knot//net.minecraft.world.entity.boss.enderdragon.phases.EnderDragonPhase.<clinit>(EnderDragonPhase.java:13)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method getLandingPos(Lnet/minecraft/class_2338;)Lnet/minecraft/class_2338; in debugify.mixins.json:basic.mc88371.DragonLandingPhaseMixin from mod debugify failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Debugify-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_1510.method_5693(class_1510.java:159)
	at knot//net.minecraft.class_1297.<init>(class_1297.java:323)
	at knot//net.minecraft.class_1309.<init>(class_1309.java:280)
	at knot//net.minecraft.class_1308.<init>(class_1308.java:147)
	at knot//net.minecraft.class_1510.<init>(class_1510.java:104)
	at knot//net.minecraft.class_1299.method_5883(class_1299.java:597)
	at knot//net.minecraft.class_2881.method_12523(class_2881.java:494)
	at knot//net.minecraft.class_2881.method_12525(class_2881.java:305)
	at knot//net.minecraft.class_2881.method_12538(class_2881.java:251)

-- Affected level --
Details:
	All players: 1 total; [class_3222['TinyDerp'/834, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50]]
	Chunk stats: 211
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-32,64,-48), Section: (at 0,0,0 in -2,4,-3; chunk contains blocks -32,0,-48 to -17,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2525175 game time, 3402271 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 25491 (now: false), thunder time: 73217 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 1
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1744)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1072)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1575)

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Java Version: 23.0.1, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	JVM Flags: 20 total; -Xms2048M -Xmx2048M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20
	Fabric Mods: 
		audioplayer: AudioPlayer 1.21.4-1.13.1
			admiral: Admiral 0.4.7+1.21.3
		better-fabric-console: Better Fabric Console 1.2.2
			adventure-platform-fabric: adventure-platform-fabric 6.2.0
				net_kyori_adventure-api: adventure-api 4.18.0
				net_kyori_adventure-key: adventure-key 4.18.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.4
				net_kyori_adventure-platform-mod-shared-fabric-repack: adventure-platform-mod-shared-fabric-repack 6.2.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.18.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.18.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.18.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.18.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.18.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.18.0
				net_kyori_ansi: ansi 1.1.1
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
				net_kyori_option: option 1.0.0
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			net_fabricmc_mapping-io: mapping-io 0.6.1
			org_fusesource_jansi_jansi: jansi 2.4.1
			org_jline_jline: jline 3.28.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.28.0
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		betterstats: Better Statistics Screen 3.13.4+fabric-1.21.4
		c2me: Concurrent Chunk Management Engine 0.3.1+rc.1.0+1.21.4
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.1+rc.1.0+1.21.4
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.1+rc.1.0+1.21.4
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.1+rc.1.0+1.21.4
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.1+rc.1.0+1.21.4
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.1+rc.1.0+1.21.4
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.1+rc.1.0+1.21.4
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.1+rc.1.0+1.21.4
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.1+rc.1.0+1.21.4
			c2me-opts-dfc: Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.1+rc.1.0+1.21.4
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.1+rc.1.0+1.21.4
			c2me-opts-natives-math: Concurrent Chunk Management Engine (Optimizations/Natives Math) 0.3.1+rc.1.0+1.21.4
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.1+rc.1.0+1.21.4
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.1+rc.1.0+1.21.4
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.1+rc.1.0+1.21.4
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.1+rc.1.0+1.21.4
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.1+rc.1.0+1.21.4
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.1+rc.1.0+1.21.4
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.1+rc.1.0+1.21.4
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.1+rc.1.0+1.21.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		chunky: Chunky 1.4.27
		debugify: Debugify 1.21.4+1.0
		fabric-api: Fabric API 0.112.2+1.21.4
			fabric-api-base: Fabric API Base 0.4.54+b47eab6b04
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.86+b1caf1e904
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.5+b1caf1e904
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.62+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.41+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.79+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.14+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.9+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.9+3d1fb53904
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.6+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.2.2+20ea1e2304
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.12+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.2+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.14+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.23+7feeb73304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.4+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.33+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.21+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.25+7feeb73304
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.9+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.8+d70d2c0604
			fabric-particles-v1: Fabric Particles (v1) 4.0.14+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.5+b1caf1e904
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.2+3d1fb53904
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.19+7feeb73304
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.109+7feeb73304
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.2+20ea1e2304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.8+b1caf1e904
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fabricproxy-lite: FabricProxy Lite 2.9.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		ferritecore: FerriteCore 7.1.1
		java: OpenJDK 64-Bit Server VM 23
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lithium: Lithium 0.14.3+mc1.21.4
		minecraft: Minecraft 1.21.4
		mru: Mineblock's Repeated Utilities 1.0.7+1.21.4+fabric
		noisium: Noisium 2.5.0+mc1.21.4
		scalablelux: ScalableLux 0.1.2+beta.1+fabric.6d46f24
		snowundertrees: Snow Under Trees 2.6.0+1.21.4
			yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21.4-fabric
				com_twelvemonkeys_common_common-image: common-image 3.12.0
				com_twelvemonkeys_common_common-io: common-io 3.12.0
				com_twelvemonkeys_common_common-lang: common-lang 3.12.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		tcdcommons: TCD Commons API 3.12.5+fabric-1.21.4
		vcinteraction: Voice Chat Interaction 1.21.4-1.0.8
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.11.0+1.21.4-rc1
		vmp: Very Many Players 0.2.0+beta.7.187+1.21.4
		voicechat: Simple Voice Chat 1.21.4-2.5.27
	Server Running: true
	Player Count: 2 / 20; [class_3222['TaffieQ'/3, l='ServerLevel[world]', x=-1854.99, y=-12.00, z=-683.09], class_3222['TinyDerp'/834, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50]]
	Active Data Packs: vanilla, minecart_improvements, fabric, audioplayer, fabric-convention-tags-v2, snowundertrees, vcinteraction
	Available Data Packs: audioplayer, fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, snowundertrees, trade_rebalance, vanilla, vcinteraction
	Enabled Feature Flags: minecraft:vanilla, minecraft:minecart_improvements
	World Generation: Stable
	World Seed: -3889398926040997645
	Suppressed Exceptions: ~~NONE~~
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by BlueGradientHorizon** [comment]
Why did you close this issue? Isn't it still relevant?
