### ISSUE TITLE
[Bug] Crash on startup (quilt)

### ISSUE THREAD

**Issue by Ayuma-cell** [isXander/Debugify#91]
### Bug Description

Crash log is not really helpful here. MC-234898 is already disabled that by itself already fixed like 3 errors. But crash still occurs.

### How to Reproduce?

1. Enable Debugify in Quilt
2. optionally disable MC-234898

### Expected Behavior

A normal startup

### Version

1.10.0

### Mod Loader Version

1.18.2 - Quilt 0.16.1-beta.3

### Mod Loader

Quilt

### Logs or additional context

```
[27/05/2022 16:07:53 pm] [main/INFO] Loading Minecraft 1.18.2 with Quilt Loader 0.16.1-beta.3
[27/05/2022 16:07:53 pm] [ForkJoinPool-1-worker-9/WARN] Neither a fabric nor a quilt JAR at "**USERSDIR**\instances\Infinia-Dev\mods\AttributeFix-Forge-1.18.2-14.0.1.jar", ignoring
[27/05/2022 16:07:53 pm] [ForkJoinPool-1-worker-8/WARN] Warnings for mod "com_github_wearblackallday_javautils"'s mod json:- Version bd58640372 does not respect SemVer -- comparison support is limited. "version" at  at line 4 column 26 path $.version
[27/05/2022 16:07:53 pm] [ForkJoinPool-1-worker-3/WARN] Warnings for mod "regrowth"'s mod json:- Version 0.30c.release does not respect SemVer -- comparison support is limited. "version" at  at line 4 column 29 path $.version
[27/05/2022 16:07:53 pm] [ForkJoinPool-1-worker-1/WARN] Neither a fabric nor a quilt JAR at "**USERSDIR**\instances\Infinia-Dev\mods\MouseTweaks-forge-mc1.18-2.22.jar", ignoring
[27/05/2022 16:07:53 pm] [ForkJoinPool-1-worker-6/WARN] Warnings for mod "terrablender"'s mod json:- Version 1.1.0.99 has more than 3 version components, which may not be fully supported. "version" at  at line 4 column 24 path $.version
[27/05/2022 16:07:53 pm] [ForkJoinPool-1-worker-2/WARN] Neither a fabric nor a quilt JAR at "**USERSDIR**\instances\Infinia-Dev\mods\ToolStats-Forge-1.18.2-9.0.1.jar", ignoring
[27/05/2022 16:07:54 pm] 	- additionaladditions 4.0.3
[27/05/2022 16:07:54 pm] 	- additionalentityattributes 1.0.0+1.18.2
[27/05/2022 16:07:54 pm] 	- adorn 3.5.0+1.18.2
[27/05/2022 16:07:54 pm] 	- advanced_runtime_resource_pack 0.5.5
[27/05/2022 16:07:54 pm] 	- amecs 1.3.7+mc.1.18.2
[27/05/2022 16:07:54 pm] 	- amecsapi 1.3.5+mc22w06a
[27/05/2022 16:07:54 pm] 	- apoli 2.3.3
[27/05/2022 16:07:54 pm] 	- appleskin 2.4.0+mc1.18.2
[27/05/2022 16:07:54 pm] 	- apugli 1.6.2
[27/05/2022 16:07:54 pm] 	- architectury 4.4.64
[27/05/2022 16:07:54 pm] 	- armorpointspp 3.0.1
[27/05/2022 16:07:54 pm] 	- automated_crafting 1.4.4
[27/05/2022 16:07:54 pm] 	- badpackets 0.1.2
[27/05/2022 16:07:54 pm] 	- betteranimalsplus 1.18.2-11.0.5
[27/05/2022 16:07:54 pm] 	- betterdungeons 1.18.2-Fabric-2.1.0
[27/05/2022 16:07:54 pm] 	- bettermineshafts 1.18.2-Fabric-2.1.1
[27/05/2022 16:07:54 pm] 	- betterstrongholds 1.18.2-Fabric-2.1.1
[27/05/2022 16:07:54 pm] 	- blue_endless_jankson 1.2.1
[27/05/2022 16:07:54 pm] 	- bobby 3.1.1
[27/05/2022 16:07:54 pm] 	- bosses_of_mass_destruction 1.3.7-1.18.2
[27/05/2022 16:07:54 pm] 	- byg 1.4
[27/05/2022 16:07:54 pm] 	- caffeineconfig 1.1.0
[27/05/2022 16:07:54 pm] 	- calio 1.5.1
[27/05/2022 16:07:54 pm] 	- cardinal-components 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-base 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-block 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-chunk 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-entity 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-item 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-level 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-scoreboard 4.1.4
[27/05/2022 16:07:54 pm] 	- cardinal-components-world 4.1.4
[27/05/2022 16:07:54 pm] 	- charmonium 4.0.0
[27/05/2022 16:07:54 pm] 	- chunky 1.2.164
[27/05/2022 16:07:54 pm] 	- clickthrough 1.18.2-fabric0.47.10-0.4
[27/05/2022 16:07:54 pm] 	- cloth-basic-math 0.6.0
[27/05/2022 16:07:54 pm] 	- cloth-config 6.2.57
[27/05/2022 16:07:54 pm] 	- cloth-config-lite 2.0.6
[27/05/2022 16:07:54 pm] 	- com_electronwill_night-config_core 3.6.5
[27/05/2022 16:07:54 pm] 	- com_electronwill_night-config_toml 3.6.5
[27/05/2022 16:07:54 pm] 	- com_eliotlash_mclib_mclib 18
[27/05/2022 16:07:54 pm] 	- com_eliotlash_molang_molang 18
[27/05/2022 16:07:54 pm] 	- com_github_luben_zstd-jni 1.5.2-2
[27/05/2022 16:07:54 pm] 	- com_github_wearblackallday_javautils bd58640372
[27/05/2022 16:07:54 pm] 	- com_moandjiezana_toml_toml4j 0.7.2
[27/05/2022 16:07:54 pm] 	- com_neovisionaries_nv-websocket-client 2.14
[27/05/2022 16:07:54 pm] 	- com_typesafe_config 1.4.2
[27/05/2022 16:07:54 pm] 	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
[27/05/2022 16:07:54 pm] 	- connectivity 1.18.2-2.9
[27/05/2022 16:07:54 pm] 	- consistency_plus 0.5.0+1.18.2
[27/05/2022 16:07:54 pm] 	- cropxp 1.18.2-1.2.0
[27/05/2022 16:07:54 pm] 	- crowdin-translate 1.4+1.18.2
[27/05/2022 16:07:54 pm] 	- cullleaves 2.3.2
[27/05/2022 16:07:54 pm] 	- customportalapi 0.0.1-beta50-1.18
[27/05/2022 16:07:54 pm] 	- dark-enchanting 1.0.0+1.18.2
[27/05/2022 16:07:54 pm] 	- dashloader 3.1.1+1.18
[27/05/2022 16:07:54 pm] 	- debugify 1.10.0
[27/05/2022 16:07:54 pm] 	- denseores 1.2.2+1.18.2
[27/05/2022 16:07:54 pm] 	- dev_quantumfusion_dashloader_dashloader-core 1.4.0
[27/05/2022 16:07:54 pm] 	- dev_quantumfusion_hyphen 0.2.0
[27/05/2022 16:07:54 pm] 	- dimores 1.0.2
[27/05/2022 16:07:54 pm] 	- dimthread 1.2.6
[27/05/2022 16:07:54 pm] 	- dusk 1.18.2-1.9
[27/05/2022 16:07:54 pm] 	- dynamicfps 2.1.0
[27/05/2022 16:07:54 pm] 	- dynview 1.18.2-2.1
[27/05/2022 16:07:54 pm] 	- eldritch_mobs 1.11.0
[27/05/2022 16:07:54 pm] 	- ellemes_container_lib 1.4.0-beta.2
[27/05/2022 16:07:54 pm] 	- enhancedblockentities 0.6+1.18.2
[27/05/2022 16:07:54 pm] 	- entity-view-distance 1.0.1+1.18.2
[27/05/2022 16:07:54 pm] 	- entityculling 1.5.1
[27/05/2022 16:07:54 pm] 	- expanded_armor_enchanting 1.0.2
[27/05/2022 16:07:54 pm] 	- expanded_axe_enchanting 1.0.3
[27/05/2022 16:07:54 pm] 	- expanded_trident_enchanting 1.0.3
[27/05/2022 16:07:54 pm] 	- expanded_weapon_enchanting 1.0.2
[27/05/2022 16:07:54 pm] 	- expandedstorage 7.4.0-beta.2
[27/05/2022 16:07:54 pm] 	- extrakeybinds 0.2.0
[27/05/2022 16:07:54 pm] 	- extraorigins 1.18-10
[27/05/2022 16:07:54 pm] 	- fabric-language-kotlin 1.7.4+kotlin.1.6.21
[27/05/2022 16:07:54 pm] 	- fabric-permissions-api-v0 0.1-SNAPSHOT
[27/05/2022 16:07:54 pm] 	- fallingleaves 1.11.1+1.18.2
[27/05/2022 16:07:54 pm] 	- fallingtree 3.5.1
[27/05/2022 16:07:54 pm] 	- ferritecore 4.2.1
[27/05/2022 16:07:54 pm] 	- fiber 0.23.0-2
[27/05/2022 16:07:54 pm] 	- figura 0.0.8+1.18.2
[27/05/2022 16:07:54 pm] 	- flan 1.18.2-1.7.7
[27/05/2022 16:07:54 pm] 	- forgeconfigapiport 3.2.0
[27/05/2022 16:07:54 pm] 	- gbfabrictools 1.3.4+1.18.2
[27/05/2022 16:07:54 pm] 	- geckolib3 3.0.39
[27/05/2022 16:07:54 pm] 	- genesis 1.18.2-1.0.1
[27/05/2022 16:07:54 pm] 	- globaldataandresourcepacks 1.12.2
[27/05/2022 16:07:54 pm] 	- graveyard 1.8
[27/05/2022 16:07:54 pm] 	- grounded_origins 1.1.3
[27/05/2022 16:07:54 pm] 	- gud_recipe_confidence 1.0.2
[27/05/2022 16:07:54 pm] 	- iknowwhatimdoing 4.0.0
[27/05/2022 16:07:54 pm] 	- illagerexp 0.1.5
[27/05/2022 16:07:54 pm] 	- incantationem 1.1.3+1.18.2
[27/05/2022 16:07:54 pm] 	- incendium 5.0.3
[27/05/2022 16:07:54 pm] 	- incubus_core 1.6.6+1.18.2
[27/05/2022 16:07:54 pm] 	- indium 1.0.3+mc1.18.2
[27/05/2022 16:07:54 pm] 	- inventoryprofilesnext 1.4.0
[27/05/2022 16:07:54 pm] 	- io_leangen_geantyref_geantyref 1.3.13
[27/05/2022 16:07:54 pm] 	- iris 1.2.4-build.38
[27/05/2022 16:07:54 pm] 	- jankson 4.0.0+j1.2.0
[27/05/2022 16:07:54 pm] 	- java 17
[27/05/2022 16:07:54 pm] 	- kanos_config 0.3.1+1.14.4-1.19
[27/05/2022 16:07:54 pm] 	- kirin 1.10.0
[27/05/2022 16:07:54 pm] 	- krypton 0.1.9
[27/05/2022 16:07:54 pm] 	- lambdynlights 2.1.0+1.17
[27/05/2022 16:07:54 pm] 	- lazydfu 0.1.2
[27/05/2022 16:07:54 pm] 	- libblockattributes 0.10.2
[27/05/2022 16:07:54 pm] 	- libblockattributes_core 0.10.2
[27/05/2022 16:07:54 pm] 	- libblockattributes_fluids 0.10.2
[27/05/2022 16:07:54 pm] 	- libblockattributes_items 0.10.2
[27/05/2022 16:07:54 pm] 	- libgui 5.4.0+1.18.2
[27/05/2022 16:07:54 pm] 	- libmultipart 0.7.2
[27/05/2022 16:07:54 pm] 	- libnetworkstack 0.6.0
[27/05/2022 16:07:54 pm] 	- libninepatch 1.1.0
[27/05/2022 16:07:54 pm] 	- lithium 0.7.10
[27/05/2022 16:07:54 pm] 	- maelstrom_library 1.2.4-1.18.2
[27/05/2022 16:07:54 pm] 	- megane 7.5.1
[27/05/2022 16:07:54 pm] 	- megane-api 7.1.0
[27/05/2022 16:07:54 pm] 	- megane-fabric-transfer 7.1.0
[27/05/2022 16:07:54 pm] 	- megane-lib-block-attributes 7.1.0
[27/05/2022 16:07:54 pm] 	- megane-runtime 7.2.0
[27/05/2022 16:07:54 pm] 	- megane-vanilla 7.1.1
[27/05/2022 16:07:54 pm] 	- midnightlib 0.2.9
[27/05/2022 16:07:54 pm] 	- minecraft 1.18.2
[27/05/2022 16:07:54 pm] 	- mm 2.3
[27/05/2022 16:07:54 pm] 	- moborigins 1.8.1
[27/05/2022 16:07:58 pm] [main/INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Ayes/AppData/Roaming/ATLauncher/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[27/05/2022 16:07:58 pm] [main/INFO] Compatibility level set to JAVA_17
[27/05/2022 16:07:59 pm] [main/INFO] Preparing DashLoader 3.1.1+1.18.
[27/05/2022 16:07:59 pm] [main/WARN] Disabled Optional Feature FAST_STATE_INIT from dashloader config. DashLoader
[27/05/2022 16:07:59 pm] [main/WARN] Disabled Optional Feature CACHE_PARTICLE from dashloader config. DashLoader
[27/05/2022 16:07:59 pm] [main/WARN] [Satin] Sodium is present, custom block renders may not work
[27/05/2022 16:07:59 pm] [main/WARN] Reference map 'rhino-fabric-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[27/05/2022 16:07:59 pm] [main/INFO] Loaded configuration file for Sodium Extra: 23 options available, 0 override(s) found
[27/05/2022 16:07:59 pm] [main/WARN] Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[27/05/2022 16:07:59 pm] [main/WARN] Reference map 'yungsbridges.refmap.json' for yungsbridges_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[27/05/2022 16:07:59 pm] [main/WARN] Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[27/05/2022 16:07:59 pm] [main/WARN] Reference map 'yungsextras.refmap.json' for yungsextras_fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[27/05/2022 16:07:59 pm] [main/INFO] Loaded configuration file for Lithium: 102 options available, 3 override(s) found
[27/05/2022 16:07:59 pm] [main/INFO] Loaded configuration file for Sodium: 29 options available, 4 override(s) found
[27/05/2022 16:07:59 pm] [main/WARN] Reference map 'cropxp-refmap.json' for cropxp.mixins.json could not be read. If this is a development environment you can ignore this message
[27/05/2022 16:07:59 pm] 	at cc.woverflow.debugify.utils.MixinPlugin.onLoad(MixinPlugin.java:23)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:244)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:147)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:181)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:159)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:70)
[27/05/2022 16:07:59 pm] 	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
[27/05/2022 16:07:59 pm] Caused by: java.lang.ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
[27/05/2022 16:07:59 pm] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[27/05/2022 16:07:59 pm] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[27/05/2022 16:07:59 pm] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[27/05/2022 16:07:59 pm] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[27/05/2022 16:07:59 pm] 	... 16 more
[27/05/2022 16:07:59 pm] [main/WARN] Mixin transformation of net.fabricmc.loader.launch.knot.UnusedEmptyTargetClass failed
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:249)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:147)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:181)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:159)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:70)
[27/05/2022 16:07:59 pm] 	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
[27/05/2022 16:07:59 pm] Caused by: java.lang.NoClassDefFoundError: com/llamalad7/mixinextras/MixinExtrasBootstrap
[27/05/2022 16:07:59 pm] 	at cc.woverflow.debugify.utils.MixinPlugin.onLoad(MixinPlugin.java:23)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[27/05/2022 16:07:59 pm] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:244)
[27/05/2022 16:07:59 pm] 	... 6 more
[27/05/2022 16:07:59 pm] Caused by: java.lang.ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
[27/05/2022 16:07:59 pm] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[27/05/2022 16:07:59 pm] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[27/05/2022 16:07:59 pm] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[27/05/2022 16:07:59 pm] 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[27/05/2022 16:07:59 pm] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[27/05/2022 16:07:59 pm] 	... 16 more
[27/05/2022 16:07:59 pm] [main/ERROR] Uncaught exception in thread "main"
```

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Cannot repeat

**Comment by isXander** [comment]
Does it work without any mods apart from the essentials like sodium etc?

**Comment by duplexsystem** [comment]
only happens server side for me. clients load fine

**Comment by isXander** [comment]
Still apply on 1.11.0?

**Comment by Ayuma-cell** [comment]
Can't test it with the exact same setup rn. However on it's own it seems to be working fine

**Comment by isXander** [comment]
No

**Comment by Ayuma-cell** [comment]
Well since the issue seems to be resolved I'm going to close this now ^-^ Thanks for you help.
